// ── i18n ──────────────────────────────────────
const I18N = {
  en: {
    unlocks: 'Unlocks', requires: 'Requires',
    legReq: 'Required', legOr: 'Any of',
    orReq: 'any of', andReq: 'required',
    eraUnlock: 'Era Unlock', wonder: 'Wonder',
    labelBeaker: 'Beakers', labelCost: 'Coins',
    era1: 'Ancient', era2: 'Classical', era3: 'Antiquity',
    era4: 'Medieval', era5: 'Renaissance', era6: 'Industrial',
    eraW: 'Wonders',
    chainCost: 'Chain Cost', chainRemaining: 'Remaining to research',
    chainSkippedBc: 'skipped', chainSkippedCost: 'skipped',
    researchTime: 'research time',
    queueTitle: 'Research Queue', queueClear: 'Clear',
    queueAdd: '+ Add to Queue', queueRemove: '− Remove from Queue',
    queueEmpty: 'Queue is empty',
    queueError: 'Cannot queue — dependency not ready:',
    queueTotal: 'Total remaining:',
    cityTitle: 'City Settings',
    cityBeakers: 'Beakers per hour',
    cityBeakersHint: 'Used to calculate research time',
    cityTowns: 'Count Towns',
    cityTownsHint: 'Each town adds +10% to beaker cost',
    searchPlaceholder: 'Search…',
    viewAll: 'All', viewDone: '✓ Checked', viewUndone: '○ Unchecked',
  },
  ru: {
    unlocks: 'Открывает', requires: 'Требует',
    legReq: 'Обязательно', legOr: 'Любое из',
    orReq: 'любое из', andReq: 'обязательно',
    eraUnlock: 'Эпоха', wonder: 'Чудо',
    labelBeaker: 'Наука', labelCost: 'Монеты',
    era1: 'Древняя', era2: 'Классическая', era3: 'Античность',
    era4: 'Средневековье', era5: 'Ренессанс', era6: 'Индустриальная',
    eraW: 'Чудеса',
    chainCost: 'Стоимость цепочки', chainRemaining: 'Осталось исследовать',
    chainSkippedBc: 'пропущено', chainSkippedCost: 'пропущено',
    researchTime: 'время исследования',
    queueTitle: 'Очередь исследований', queueClear: 'Очистить',
    queueAdd: '+ В очередь', queueRemove: '− Убрать из очереди',
    queueEmpty: 'Очередь пуста',
    queueError: 'Нельзя добавить — зависимость не готова:',
    queueTotal: 'Итого осталось:',
    cityTitle: 'Настройки города',
    cityBeakers: 'Наука в час',
    cityBeakersHint: 'Используется для расчёта времени исследования',
    cityTowns: 'Количество городов',
    cityTownsHint: 'Каждый город добавляет +10% к стоимости науки',
    searchPlaceholder: 'Поиск…',
    viewAll: 'Все', viewDone: '✓ Изучено', viewUndone: '○ Не изучено',
  }
};

const ERA_COLORS = { 1: '#4a90c4', 2: '#56b87a', 3: '#c8832a', 4: '#c44b7a', 5: '#7a5bc4', 6: '#c45050', 0: '#c8a84b' };

// ── Tech data ─────────────────────────────────
const TECHS = [
  { id: 'tech_ancient_era', name: 'Ancient Era', era: 1, bc: 0, cost: 0, req: null, unlock_era: true, desc: 'Unlocks Policies, Explorer Unit, Lumberjack Unit, Miner Unit' },
  { id: 'tech_belief', name: 'Belief', era: 1, bc: 25, cost: 25, req: 'tech_ancient_era', desc: 'Unlocks Monument' },
  { id: 'tech_mining', name: 'Mining', era: 1, bc: 1000, cost: 2500, req: 'tech_belief', desc: 'Unlocks Trommel' },
  { id: 'tech_agriculture', name: 'Agriculture', era: 1, bc: 1000, cost: 2500, req: 'tech_belief', desc: 'Unlocks Farm' },
  { id: 'tech_laws', name: 'Laws', era: 1, bc: 1000, cost: 2500, req: 'tech_belief', desc: 'Unlocks Bank' },
  { id: 'tech_pantheon', name: 'Pantheon', era: 1, bc: 1000, cost: 2500, req: 'tech_belief', desc: 'Unlocks Altar' },
  { id: 'tech_classical_era', name: 'Classical Era', era: 2, bc: 1750, cost: 5000, req: 'tech_mining/tech_agriculture/tech_laws/tech_pantheon', unlock_era: true, desc: 'Unlocks +2 Unit Level, Civics' },
  { id: 'tech_artisanship', name: 'Artisanship', era: 2, bc: 2500, cost: 5000, req: 'tech_classical_era', desc: "Unlocks Forge, Archer's Workshop, Tier 1 Metal, Tier 1 Sword, Tier 1 Enderbow" },
  { id: 'tech_iron_working', name: 'Iron Working', era: 2, bc: 2500, cost: 5000, req: 'tech_classical_era', desc: 'Unlocks Tier 1 Bow, Tier 1 Crossbow, Tier 1 Axe, Tier 1 Shield' },
  { id: 'tech_armory', name: 'Armory', era: 2, bc: 2500, cost: 5000, req: 'tech_classical_era:tech_mining', desc: 'Unlocks Barracks, Warrior Unit, Archer Unit, Hoplite Unit' },
  { id: 'tech_productivity', name: 'Productivity', era: 2, bc: 2500, cost: 5000, req: 'tech_classical_era:tech_mining', desc: 'Unlocks Mine, Tree Farm' },
  { id: 'tech_pottery', name: 'Pottery', era: 2, bc: 2500, cost: 5000, req: 'tech_classical_era:tech_agriculture', desc: 'Unlocks Granary, Cottage' },
  { id: 'tech_calendar', name: 'Calendar', era: 2, bc: 2500, cost: 5000, req: 'tech_classical_era:tech_laws', desc: 'Unlocks Library' },
  { id: 'tech_state_workforce', name: 'State Workforce', era: 2, bc: 2500, cost: 5000, req: 'tech_classical_era:tech_laws', desc: 'Unlocks Hamlet' },
  { id: 'tech_brewing', name: 'Brewing', era: 2, bc: 5000, cost: 7500, req: 'tech_classical_era:tech_pantheon', desc: 'Unlocks Alchemy Store' },
  { id: 'tech_masonry', name: 'Masonry', era: 2, bc: 5000, cost: 7500, req: 'tech_armory:tech_productivity', desc: 'Unlocks Arrow Tower, Arrow Tower Walls, Scout Tower, Scout Tower Walls and Upgrade Civilization Project' },
  { id: 'tech_toolsmithing', name: 'Toolsmithing', era: 2, bc: 5000, cost: 7500, req: 'tech_productivity', desc: 'Unlocks Smeltery, Fletchery' },
  { id: 'tech_the_wheel', name: 'The Wheel', era: 2, bc: 5000, cost: 7500, req: 'tech_pottery', desc: 'Unlocks Windmill, Sawmill, +20 Growth per Culture Zone' },
  { id: 'tech_animal_husbandry', name: 'Animal Husbandry', era: 2, bc: 5000, cost: 7500, req: 'tech_pottery', desc: 'Unlocks Pasture, Stable' },
  { id: 'tech_code_of_laws', name: 'Code of Laws', era: 2, bc: 5000, cost: 7500, req: 'tech_state_workforce', desc: 'Unlocks Village, +10% coins from Quests' },
  { id: 'tech_construction_site', name: 'Construction Site', era: 2, bc: 10000, cost: 10000, req: 'tech_toolsmithing', desc: 'Unlocks Quarry, Trommel Level' },
  { id: 'tech_land_taxes', name: 'Land Taxes', era: 2, bc: 10000, cost: 10000, req: 'tech_the_wheel:tech_animal_husbandry', desc: 'Unlocks +10% Cottage income, Cottage Level' },
  { id: 'tech_trading', name: 'Trading', era: 2, bc: 10000, cost: 10000, req: 'tech_animal_husbandry', desc: 'Unlocks Trade Outpost, Tree Farm Level' },
  { id: 'tech_writing', name: 'Writing', era: 2, bc: 10000, cost: 10000, req: 'tech_calendar', desc: 'Unlocks Bank Level, Cottage Level' },
  { id: 'tech_monarchy', name: 'Monarchy', era: 2, bc: 10000, cost: 10000, req: 'tech_code_of_laws:tech_brewing', desc: 'Unlocks Large Village, Cottage Level' },
  { id: 'tech_antiquity_era', name: 'Antiquity Era', era: 3, bc: 15000, cost: 15000, req: 'tech_construction_site/tech_land_taxes/tech_trading/tech_writing/tech_monarchy', unlock_era: true, desc: 'Unlocks Settler Unit, +2 Unit Level, +1 active Warlord Limit, +1 Wonder research slot' },
  { id: 'tech_steel_working', name: 'Steel Working', era: 3, bc: 17500, cost: 15000, req: 'tech_antiquity_era:tech_iron_working', desc: 'Unlocks Tier 2 Bow, Tier 2 Crossbow, Tier 2 Axe, Tier 2 Shield' },
  { id: 'tech_craftsmanship', name: 'Craftsmanship', era: 3, bc: 17500, cost: 15000, req: 'tech_antiquity_era:tech_artisanship', desc: 'Unlocks Tier 2 leather, Tier 2 Metal, Tier 2 Sword, Tier 2 Enderbow' },
  { id: 'tech_castles', name: 'Castles', era: 3, bc: 17500, cost: 15000, req: 'tech_antiquity_era:tech_masonry', desc: 'Unlocks Wall, +10 HP to Control Points' },
  { id: 'tech_military_tradition', name: 'Military Tradition', era: 3, bc: 17500, cost: 15000, req: 'tech_antiquity_era:tech_masonry', desc: 'Unlocks Engineer Unit, Military unit promotions' },
  { id: 'tech_deep_mining', name: 'Deep Mining', era: 3, bc: 17500, cost: 15000, req: 'tech_antiquity_era:tech_construction_site:tech_land_taxes', desc: 'Unlocks Quarry Level, Mine Level' },
  { id: 'tech_commerce', name: 'Commerce', era: 3, bc: 17500, cost: 15000, req: 'tech_antiquity_era:tech_toolsmithing:tech_land_taxes:tech_trading', desc: 'Unlocks Pasture Level, Tree Farm Level' },
  { id: 'tech_horseback_riding', name: 'Horseback Riding', era: 3, bc: 17500, cost: 15000, req: 'tech_antiquity_era:tech_trading', desc: 'Unlocks Pasture Level, +20% travel range' },
  { id: 'tech_minting', name: 'Minting', era: 3, bc: 17500, cost: 15000, req: 'tech_antiquity_era:tech_writing', desc: 'Unlocks Bank Level, +10% Cottage income' },
  { id: 'tech_barter', name: 'Barter', era: 3, bc: 17500, cost: 15000, req: 'tech_antiquity_era:tech_trading', desc: 'Unlocks Bank Level, Market' },
  { id: 'tech_early_empire', name: 'Early Empire', era: 3, bc: 17500, cost: 15000, req: 'tech_antiquity_era:tech_monarchy', desc: 'Unlocks Cottage Level, Warehouse' },
  { id: 'tech_foundation', name: 'Foundation', era: 3, bc: 30000, cost: 20000, req: 'tech_castles:tech_deep_mining', desc: 'Unlocks Your tile improvement start one level higher, Tower Level, Windmill Level' },
  { id: 'tech_sifting', name: 'Sifting', era: 3, bc: 30000, cost: 20000, req: 'tech_military_tradition:tech_deep_mining', desc: 'Unlocks Trommel Level, Smeltery Level' },
  { id: 'tech_sailing', name: 'Sailing', era: 3, bc: 30000, cost: 20000, req: 'tech_commerce', desc: 'Unlocks Shipyard, Fishing Boat' },
  { id: 'tech_conservation', name: 'Conservation', era: 3, bc: 30000, cost: 20000, req: 'tech_horseback_riding:tech_minting', desc: 'Unlocks Butchery' },
  { id: 'tech_priesthood', name: 'Priesthood', era: 3, bc: 30000, cost: 20000, req: 'tech_barter:tech_early_empire', desc: 'Unlocks Temple, Alchemy Store Level' },
  { id: 'tech_guilds', name: 'Guilds', era: 3, bc: 30000, cost: 20000, req: 'tech_early_empire', desc: 'Unlocks Bank Level, Adventurers Guild' },
  { id: 'tech_logistic', name: 'Logistic', era: 3, bc: 55000, cost: 40000, req: 'tech_foundation', desc: 'Unlocks Temple Level' },
  { id: 'tech_gunpowder', name: 'Gunpowder', era: 3, bc: 55000, cost: 40000, req: 'tech_foundation', desc: 'Unlocks Cannon Tower, Cannon Tower Walls, Tree Farm Level, +0.25 hammer per plain and desert chunk' },
  { id: 'tech_open_field_excavation', name: 'Open Field Excavation', era: 3, bc: 55000, cost: 40000, req: 'tech_sifting:tech_sailing', desc: 'Unlocks Mine Level, Quarry Level, +15 Culture per Culture Zone' },
  { id: 'tech_aquaculture', name: 'Aquaculture', era: 3, bc: 55000, cost: 40000, req: 'tech_sailing', desc: 'Unlocks Alchemy Store Level, Fletchery Level, Windmill Level, +0.25 growth per Savannah and Mesa chunk' },
  { id: 'tech_baking', name: 'Baking', era: 3, bc: 55000, cost: 40000, req: 'tech_sailing:tech_horseback_riding', desc: 'Unlocks Bakery, Pasture Level' },
  { id: 'tech_printing_press', name: 'Printing Press', era: 3, bc: 55000, cost: 40000, req: 'tech_conservation:tech_priesthood', desc: 'Unlocks +10% Culture Rate' },
  { id: 'tech_scholarship', name: 'Scholarship', era: 3, bc: 55000, cost: 40000, req: 'tech_conservation:tech_guilds', desc: 'Unlocks Library Level, Alchemy Store Level' },
  { id: 'tech_global_trade', name: 'Global Trade', era: 3, bc: 55000, cost: 40000, req: 'tech_priesthood', desc: 'Unlocks +1 similar trade good income multiplier' },
  { id: 'tech_feudalism', name: 'Feudalism', era: 3, bc: 55000, cost: 40000, req: 'tech_guilds', desc: 'Unlocks Town, Cottage Level' },
  { id: 'tech_medieval_era', name: 'Medieval Era', era: 4, bc: 125000, cost: 125000, req: 'tech_logistic/tech_gunpowder/tech_open_field_excavation/tech_aquaculture/tech_baking/tech_printing_press/tech_scholarship/tech_global_trade/tech_feudalism', unlock_era: true, desc: 'Unlocks +2 Unit Level, +1 active Warlord Limit, +1 Wonder research slot, Allow buying of Economic victory point every 7 days, Government change allowed (City States), 15% beaker/coin discount for technology' },
  { id: 'tech_carbide_working', name: 'Carbide Working', era: 4, bc: 100000, cost: 150000, req: 'tech_medieval_era:tech_steel_working', desc: 'Unlocks Tier 3 Bow, Tier 3 Crossbow, Tier 3 Axe, Tier 3 Shield' },
  { id: 'tech_chemical_bonding', name: 'Chemical Bonding', era: 4, bc: 100000, cost: 150000, req: 'tech_medieval_era:tech_craftsmanship', desc: 'Unlocks Tier 3 Metal, Tier 3 Leather, Tier 3 Sword, Tier 3 Enderbow' },
  { id: 'tech_philosophy', name: 'Philosophy', era: 4, bc: 100000, cost: 100000, req: 'tech_medieval_era:tech_logistic', desc: 'Unlocks Cottage Level, Library Level' },
  { id: 'tech_mining_guilds', name: 'Mining Guilds', era: 4, bc: 100000, cost: 100000, req: 'tech_medieval_era:tech_gunpowder:tech_open_field_excavation', desc: 'Unlocks Mine Level, Smeltery Level, +10% Bank Rate' },
  { id: 'tech_rationalism', name: 'Rationalism', era: 4, bc: 100000, cost: 100000, req: 'tech_medieval_era:tech_aquaculture', desc: 'Unlocks Lab, Alchemy Store Level' },
  { id: 'tech_exploration', name: 'Exploration', era: 4, bc: 100000, cost: 100000, req: 'tech_medieval_era:tech_aquaculture', desc: 'Unlocks Lighthouse, Scout Ship' },
  { id: 'tech_ritual', name: 'Ritual', era: 4, bc: 100000, cost: 100000, req: 'tech_medieval_era:tech_printing_press', desc: 'Unlocks Temple Level, Marketplace Level' },
  { id: 'tech_currency', name: 'Currency', era: 4, bc: 100000, cost: 100000, req: 'tech_medieval_era:tech_global_trade:tech_feudalism', desc: 'Unlocks Bank Level, Butchery Level' },
  { id: 'tech_construction', name: 'Construction', era: 4, bc: 100000, cost: 100000, req: 'tech_medieval_era:tech_feudalism', desc: 'Unlocks Large Town, Marketplace Level' },
  { id: 'tech_siege_tactics', name: 'Siege Tactics', era: 4, bc: 200000, cost: 200000, req: 'tech_philosophy:tech_gunpowder', desc: 'Unlocks +1 damage against walls, Destroying a structure gives 25% of cost in coins, +0.35 beaker per forest chunk' },
  { id: 'tech_branch_mining', name: 'Branch Mining', era: 4, bc: 200000, cost: 200000, req: 'tech_mining_guilds', desc: 'Unlocks 15% smelting bonus, +0.5 hammers per Taiga & Tundra chunks' },
  { id: 'tech_turbines', name: 'Turbines', era: 4, bc: 200000, cost: 200000, req: 'tech_rationalism', desc: 'Unlocks Windmill Level, +0.25 beaker per Ocean chunk' },
  { id: 'tech_importation', name: 'Importation', era: 4, bc: 200000, cost: 200000, req: 'tech_exploration', desc: 'Unlocks +1 Happiness per Trade Good' },
  { id: 'tech_ideology', name: 'Ideology', era: 4, bc: 200000, cost: 200000, req: 'tech_exploration:tech_ritual', desc: 'Unlocks +0.25 Beaker per jungle and mushroom chunk' },
  { id: 'tech_compass', name: 'Compass', era: 4, bc: 200000, cost: 200000, req: 'tech_exploration', desc: 'Unlocks Arrow Ship, Cannon Ship, Fletchery Level' },
  { id: 'tech_education', name: 'Education', era: 4, bc: 200000, cost: 200000, req: 'tech_scholarship:tech_currency', desc: 'Unlocks Library Level, Lab Level' },
  { id: 'tech_taxation', name: 'Taxation', era: 4, bc: 200000, cost: 200000, req: 'tech_currency', desc: 'Unlocks Pasture Level, Marketplace Level' },
  { id: 'tech_urbanization', name: 'Urbanization', era: 4, bc: 200000, cost: 200000, req: 'tech_construction', desc: 'Unlocks Tower Level, Cottage Level' },
  { id: 'tech_advanced_masonry', name: 'Advanced Masonry', era: 4, bc: 200000, cost: 200000, req: 'tech_construction', desc: 'Unlocks Your Tile Improvements start one level higher, Butchery Level' },
  { id: 'tech_fortification', name: 'Fortification', era: 4, bc: 300000, cost: 400000, req: 'tech_siege_tactics:tech_branch_mining', desc: 'Unlocks Artillery Tower, Mine Level, Fletchery Level' },
  { id: 'tech_machinery', name: 'Machinery', era: 4, bc: 300000, cost: 400000, req: 'tech_branch_mining:tech_turbines', desc: 'Unlocks Cottage Level, Butchery Level, +25% speed to Bakeries and Trommels' },
  { id: 'tech_mercantile', name: 'Mercantile', era: 4, bc: 300000, cost: 400000, req: 'tech_turbines:tech_importation', desc: 'Unlocks Tavern, +10% Trade Rate' },
  { id: 'tech_inquisition', name: 'Inquisition', era: 4, bc: 300000, cost: 400000, req: 'tech_ideology:tech_compass', desc: 'Unlocks Temple Level, +0.005 happiness per beach and swamp chunk' },
  { id: 'tech_energy_study', name: 'Energy Study', era: 4, bc: 300000, cost: 400000, req: 'tech_compass:tech_education', desc: 'Unlocks Radiance Tower, Lab Level' },
  { id: 'tech_gears', name: 'Gears', era: 4, bc: 300000, cost: 400000, req: 'tech_education', desc: 'Unlocks Bakery Level, +15% Smelting bonus' },
  { id: 'tech_banking', name: 'Banking', era: 4, bc: 300000, cost: 400000, req: 'tech_taxation', desc: 'Unlocks Bank Level, +15% coin from quests' },
  { id: 'tech_nationalism', name: 'Nationalism', era: 4, bc: 300000, cost: 400000, req: 'tech_taxation:tech_urbanization', desc: 'Unlocks City, Smeltery Level' },
  { id: 'tech_sanitization', name: 'Sanitization', era: 4, bc: 300000, cost: 400000, req: 'tech_advanced_masonry', desc: 'Unlocks Hospital, Bakery Level, +1 Growth from River chunk' },
  { id: 'tech_renaissance_era', name: 'Renaissance Era', era: 5, bc: 500000, cost: 750000, req: 'tech_fortification/tech_machinery/tech_mercantile/tech_inquisition/tech_energy_study/tech_gears/tech_banking/tech_nationalism/tech_sanitization', unlock_era: true, desc: 'Unlocks +1 active Warlord Limit, +2 Unit Level, +1 Wonder research slot' },
  { id: 'tech_composite', name: 'Composite', era: 5, bc: 425000, cost: 2000000, req: 'tech_renaissance_era:tech_chemical_bonding', desc: 'Tier 4 Metal, Tier 4 Leather, Tier 4 Sword, Tier 4 Enderbow' },
  { id: 'tech_titanium_working', name: 'Titanium Working', era: 5, bc: 425000, cost: 2000000, req: 'tech_renaissance_era:tech_carbide_working', desc: 'Unlocks Tier 4 Bow, Tier 4 Crossbow, Tier 4 Axe, Tier 4 Shield' },
  { id: 'tech_communication', name: 'Communication', era: 5, bc: 425000, cost: 1000000, req: 'tech_renaissance_era:tech_fortification', desc: 'Unlocks +400 base Culture, -75% Anarchy Timer in Towns' },
  { id: 'tech_advanced_efficiency', name: 'Advanced Efficiency', era: 5, bc: 425000, cost: 1000000, req: 'tech_renaissance_era:tech_fortification', desc: 'Unlocks Library Level, +1 XP to Structures per hourly tick' },
  { id: 'tech_engineering', name: 'Engineering', era: 5, bc: 425000, cost: 1000000, req: 'tech_renaissance_era:tech_machinery', desc: "Unlocks Tower Level, +10% Structure's Hit Points" },
  { id: 'tech_replaceable_parts', name: 'Replaceable Parts', era: 5, bc: 425000, cost: 1000000, req: 'tech_renaissance_era:tech_gears:tech_machinery', desc: 'Unlocks Butchery Level, Increases hammers per Culture Zone by 20, Increase Beakers per Culture Zone by 10' },
  { id: 'tech_tourism', name: 'Tourism', era: 5, bc: 425000, cost: 1000000, req: 'tech_renaissance_era:tech_mercantile:tech_inquisition', desc: 'Unlocks Marketplace Level, +20% travel range at Stables/Shipyards' },
  { id: 'tech_civil_service', name: 'Civil Service', era: 5, bc: 425000, cost: 1000000, req: 'tech_renaissance_era:tech_mercantile:tech_gears', desc: 'Unlocks Trommel Level, Windmill Level' },
  { id: 'tech_trade_networks', name: 'Trade Networks', era: 5, bc: 425000, cost: 1000000, req: 'tech_renaissance_era:tech_energy_study:tech_banking', desc: 'Unlocks +1 similar trade good income multiplier' },
  { id: 'tech_economics', name: 'Economics', era: 5, bc: 425000, cost: 1000000, req: 'tech_renaissance_era:tech_banking', desc: 'Unlocks Bank Level' },
  { id: 'tech_agency', name: 'Agency', era: 5, bc: 425000, cost: 1000000, req: 'tech_renaissance_era:tech_nationalism', desc: 'Unlocks Lab Level, Alchemy Store Level' },
  { id: 'tech_politics', name: 'Politics', era: 5, bc: 425000, cost: 1000000, req: 'tech_renaissance_era:tech_nationalism:tech_sanitization', desc: 'Unlocks Large City, Tower Level' },
  { id: 'tech_core_mining', name: 'Core Mining', era: 5, bc: 425000, cost: 600000, req: 'tech_renaissance_era:tech_urbanization', desc: 'Unlocks Quarry Level, Trommel Level, Mine Level, Smeltery Level' },
  { id: 'tech_radio', name: 'Radio', era: 5, bc: 500000, cost: 1500000, req: 'tech_communication', desc: 'Unlocks +20% XP for units, Reduce cost of Unit Promotions by 10% (Hammer and Growth)' },
  { id: 'tech_globalization', name: 'Globalization', era: 5, bc: 500000, cost: 1500000, req: 'tech_communication:tech_advanced_efficiency', desc: 'Unlocks Temple Level, +1 Culture Zones to all towns in Civ and gain another +1 when your Town has the Metropolis Upgrade' },
  { id: 'tech_industrialization', name: 'Industrialization', era: 5, bc: 500000, cost: 1500000, req: 'tech_advanced_efficiency:tech_engineering:tech_replaceable_parts', desc: 'Unlocks Fletchery Level, +4 Tile improvement slot in every town' },
  { id: 'tech_world_trade', name: 'World Trade', era: 5, bc: 500000, cost: 1500000, req: 'tech_engineering:tech_replaceable_parts:tech_tourism', desc: 'Unlocks Bank Level, Metropolis and Capital Levels' },
  { id: 'tech_cultural_heritage', name: 'Cultural Heritage', era: 5, bc: 500000, cost: 1500000, req: 'tech_tourism:tech_trade_networks', desc: 'Unlocks Temple Level, +5% Culture Rate per Trade Good' },
  { id: 'tech_experimentation', name: 'Experimentation', era: 5, bc: 500000, cost: 1500000, req: 'tech_civil_service:tech_trade_networks', desc: 'Unlocks Arcane Tower, Lab Level' },
  { id: 'tech_stock_market', name: 'Stock Market', era: 5, bc: 500000, cost: 1500000, req: 'tech_trade_networks:tech_economics', desc: 'Unlocks Bank Level' },
  { id: 'tech_capitalism', name: 'Capitalism', era: 5, bc: 500000, cost: 1500000, req: 'tech_economics:tech_agency', desc: 'Unlocks +1 similar trade good income multiplier' },
  { id: 'tech_hydroponics', name: 'Hydroponics', era: 5, bc: 500000, cost: 1500000, req: 'tech_agency:tech_politics', desc: 'Unlocks Pasture Level, Bakery Level, Pasture require 750 growth instead of 1000 growth per bonus egg' },
  { id: 'tech_industrial_era', name: 'Industrial Era', era: 6, bc: 1000000, cost: 5000000, req: 'tech_radio/tech_globalization/tech_industrialization/tech_world_trade/tech_cultural_heritage/tech_experimentation/tech_stock_market/tech_capitalism/tech_hydroponics', unlock_era: true, desc: 'Unlocks +1 Unit Level, +1 Wonder research slot' },
  { id: 'tech_abyssal_composites', name: 'Abyssal Composite', era: 6, bc: 1000000, cost: 1500000, req: 'tech_industrial_era:tech_composite', desc: 'Tier 5 Metal, Tier 5 Leather, Tier 5 Sword, Tier 5 Enderbow' },
  { id: 'tech_abyssal_working', name: 'Abyssal Working', era: 6, bc: 1000000, cost: 2500000, req: 'tech_industrial_era:tech_titanium_working', desc: 'Unlocks Tier 5 Bow, Tier 5 Crossbow, Tier 5 Axe, Tier 5 Shield' },
  { id: 'tech_council_of_eight', name: 'Council Of Eight', era: 6, bc: 1000000, cost: 1000000, req: 'tech_industrial_era:tech_experimentation:tech_stock_market:tech_capitalism:tech_hydroponics', wonder: true, desc: 'Unlocks The Council of Eight' },
  { id: 'tech_robotics', name: 'Robotics', era: 6, bc: 2000000, cost: 2500000, req: 'tech_industrial_era:tech_abyssal_working:tech_abyssal_composites:tech_radio:tech_industrialization', desc: 'Gives you 3 Victory Points for the first level 10 military unit, Every week you gain 1 Victory Point for every different type of military unit at lvl 10' },
  { id: 'tech_enlightenment', name: 'Enlightenment', era: 6, bc: 5000000, cost: 25000000, req: 'tech_industrial_era:tech_globalization:tech_industrialization:tech_world_trade:tech_cultural_heritage', desc: 'Gives you 3 Victory Points upon completion, and grants you 1 Victory Point per week' },
];

const WONDERS = [
  { id: 'tech_great_pyramid', name: 'Great Pyramid', bc: 75000, desc: 'Unlocks The Great Pyramid' },
  { id: 'tech_great_lighthouse', name: 'Great Lighthouse', bc: 75000, desc: 'Unlocks The Great Lighthouse' },
  { id: 'tech_hanging_gardens', name: 'Hanging Gardens', bc: 75000, desc: 'Unlocks The Hanging Gardens' },
  { id: 'tech_colossus', name: 'Colossus', bc: 75000, desc: 'Unlocks The Colossus' },
  { id: 'tech_grand_ship_ingermanland', name: 'Grand Ship Ingermanland', bc: 75000, desc: 'Unlocks The Grand Ship Ingermanland' },
  { id: 'tech_taj_mahal', name: 'Taj Mahal', bc: 75000, desc: 'Unlocks The Taj Mahal' },
  { id: 'tech_temple_of_artemis', name: 'Temple of Artemis', bc: 75000, desc: 'Unlocks The Temple of Artemis' },
  { id: 'tech_statue_of_liberty', name: 'Statue of Liberty', bc: 75000, desc: 'Unlocks The Statue of Liberty' },
  { id: 'tech_notre_dame', name: 'Notre Dame', bc: 75000, desc: 'Unlocks The Notre Dame' },
  { id: 'tech_colosseum', name: 'Colosseum', bc: 75000, desc: 'Unlocks The Colosseum' },
  { id: 'tech_global_stock_exchange', name: 'Global Stock Exchange', bc: 75000, desc: 'Unlocks The Global Stock Exchange' },
  { id: 'tech_oxford_university', name: 'Oxford University', bc: 75000, desc: 'Unlocks The Oxford University' },
  { id: 'tech_himeji', name: 'Himeji Castle', bc: 75000, desc: 'Unlocks The Himeji Castle' },
  { id: 'tech_kremlin', name: 'Kremlin', bc: 75000, desc: 'Unlocks The Kremlin' },
  { id: 'tech_huey_teocalli', name: 'Huey Teocalli', bc: 75000, desc: 'Unlocks The Huey Teocalli' },
  { id: 'tech_porcelain_tower', name: 'Porcelain Tower', bc: 75000, desc: 'Unlocks The Porcelain Tower' },
  { id: 'tech_angkor_wat', name: 'Angkor Wat', bc: 75000, desc: 'Unlocks The Angkor Wat' },
  { id: 'tech_great_library', name: 'Great Library', bc: 75000, desc: 'Unlocks The Great Library' },
  { id: 'tech_chichen_itza', name: 'Chichen Itza', bc: 75000, desc: 'Unlocks The Chichen Itza' },
  { id: 'tech_big_ben', name: 'Big Ben', bc: 75000, desc: 'Unlocks The Big Ben' },
  { id: 'tech_globe_theatre', name: 'Globe Theatre', bc: 75000, desc: 'Unlocks The Globe Theatre' },
  { id: 'tech_oracle', name: 'Oracle', bc: 75000, desc: 'Unlocks The Oracle' },
  { id: 'tech_brandenburg_gate', name: 'Brandenburg Gate', bc: 75000, desc: 'Unlocks The Brandenburg Gate' },
];

const NAMES_RU = {
  'tech_ancient_era': 'Древняя Эпоха', 'tech_belief': 'Вера', 'tech_mining': 'Горное дело',
  'tech_agriculture': 'Земледелие', 'tech_laws': 'Законы', 'tech_pantheon': 'Пантеон',
  'tech_classical_era': 'Классическая Эпоха', 'tech_artisanship': 'Ремесло',
  'tech_iron_working': 'Обработка железа', 'tech_armory': 'Оружейная',
  'tech_productivity': 'Производительность', 'tech_pottery': 'Гончарство',
  'tech_calendar': 'Календарь', 'tech_state_workforce': 'Государственный труд',
  'tech_brewing': 'Пивоварение', 'tech_masonry': 'Каменная кладка',
  'tech_toolsmithing': 'Кузнечное дело', 'tech_the_wheel': 'Колесо',
  'tech_animal_husbandry': 'Скотоводство', 'tech_code_of_laws': 'Свод законов',
  'tech_construction_site': 'Стройплощадка', 'tech_land_taxes': 'Земельные налоги',
  'tech_trading': 'Торговля', 'tech_writing': 'Письмо', 'tech_monarchy': 'Монархия',
  'tech_antiquity_era': 'Античная Эпоха', 'tech_steel_working': 'Обработка стали',
  'tech_craftsmanship': 'Мастерство', 'tech_castles': 'Замки',
  'tech_military_tradition': 'Военная традиция', 'tech_deep_mining': 'Глубокая добыча',
  'tech_commerce': 'Коммерция', 'tech_horseback_riding': 'Верховая езда',
  'tech_minting': 'Чеканка монет', 'tech_barter': 'Бартер',
  'tech_early_empire': 'Ранняя империя', 'tech_foundation': 'Фундамент',
  'tech_sifting': 'Просеивание', 'tech_sailing': 'Мореплавание',
  'tech_conservation': 'Сохранение', 'tech_priesthood': 'Жречество',
  'tech_guilds': 'Гильдии', 'tech_logistic': 'Логистика', 'tech_gunpowder': 'Порох',
  'tech_open_field_excavation': 'Открытые раскопки', 'tech_aquaculture': 'Аквакультура',
  'tech_baking': 'Выпечка', 'tech_printing_press': 'Печатный станок',
  'tech_scholarship': 'Учёность', 'tech_global_trade': 'Мировая торговля',
  'tech_feudalism': 'Феодализм', 'tech_medieval_era': 'Средневековая Эпоха',
  'tech_carbide_working': 'Обработка карбида', 'tech_chemical_bonding': 'Химические связи',
  'tech_philosophy': 'Философия', 'tech_mining_guilds': 'Горняцкие гильдии',
  'tech_rationalism': 'Рационализм', 'tech_exploration': 'Исследование',
  'tech_ritual': 'Ритуал', 'tech_currency': 'Валюта', 'tech_construction': 'Строительство',
  'tech_siege_tactics': 'Осадная тактика', 'tech_branch_mining': 'Шахтная добыча',
  'tech_turbines': 'Турбины', 'tech_importation': 'Импорт', 'tech_ideology': 'Идеология',
  'tech_compass': 'Компас', 'tech_education': 'Образование', 'tech_taxation': 'Налогообложение',
  'tech_urbanization': 'Урбанизация', 'tech_advanced_masonry': 'Развитая кладка',
  'tech_fortification': 'Укрепление', 'tech_machinery': 'Механизмы',
  'tech_mercantile': 'Торговое дело', 'tech_inquisition': 'Инквизиция',
  'tech_energy_study': 'Изучение энергии', 'tech_gears': 'Шестерёнки',
  'tech_banking': 'Банковское дело', 'tech_nationalism': 'Национализм',
  'tech_sanitization': 'Санитария', 'tech_renaissance_era': 'Эпоха Ренессанса',
  'tech_composite': 'Композиты', 'tech_titanium_working': 'Обработка титана',
  'tech_communication': 'Коммуникации', 'tech_advanced_efficiency': 'Высокая эффективность',
  'tech_engineering': 'Инженерия', 'tech_replaceable_parts': 'Взаимозаменяемые детали',
  'tech_tourism': 'Туризм', 'tech_civil_service': 'Государственная служба',
  'tech_trade_networks': 'Торговые сети', 'tech_economics': 'Экономика',
  'tech_agency': 'Агентство', 'tech_politics': 'Политика',
  'tech_core_mining': 'Глубинная добыча', 'tech_radio': 'Радио',
  'tech_globalization': 'Глобализация', 'tech_industrialization': 'Индустриализация',
  'tech_world_trade': 'Мировая торговля II', 'tech_cultural_heritage': 'Культурное наследие',
  'tech_experimentation': 'Экспериментирование', 'tech_stock_market': 'Фондовый рынок',
  'tech_capitalism': 'Капитализм', 'tech_hydroponics': 'Гидропоника',
  'tech_industrial_era': 'Индустриальная Эпоха', 'tech_abyssal_composites': 'Бездонный композит',
  'tech_abyssal_working': 'Бездонная обработка', 'tech_council_of_eight': 'Совет Восьми',
  'tech_robotics': 'Робототехника', 'tech_enlightenment': 'Просвещение',
  'tech_great_pyramid': 'Великая пирамида', 'tech_great_lighthouse': 'Александрийский маяк',
  'tech_hanging_gardens': 'Висячие сады', 'tech_colossus': 'Колосс',
  'tech_grand_ship_ingermanland': 'Флагман Ингерманланд', 'tech_taj_mahal': 'Тадж-Махал',
  'tech_temple_of_artemis': 'Храм Артемиды', 'tech_statue_of_liberty': 'Статуя Свободы',
  'tech_notre_dame': 'Нотр-Дам', 'tech_colosseum': 'Колизей',
  'tech_global_stock_exchange': 'Глобальная биржа', 'tech_oxford_university': 'Оксфордский университет',
  'tech_himeji': 'Замок Химэдзи', 'tech_kremlin': 'Кремль',
  'tech_huey_teocalli': 'Уэй Теокалли', 'tech_porcelain_tower': 'Фарфоровая башня',
  'tech_angkor_wat': 'Ангкор-Ват', 'tech_great_library': 'Александрийская библиотека',
  'tech_chichen_itza': 'Чичен-Ица', 'tech_big_ben': 'Биг-Бен',
  'tech_globe_theatre': 'Глобус (Театр)', 'tech_oracle': 'Оракул',
  'tech_brandenburg_gate': 'Бранденбургские ворота',
};

const DESC_RU = {
  'tech_ancient_era': 'Открывает Политики, Разведчика, Лесоруба, Шахтёра',
  'tech_belief': 'Открывает Монумент',
  'tech_mining': 'Открывает Землечерпалку',
  'tech_agriculture': 'Открывает Ферму',
  'tech_laws': 'Открывает Банк',
  'tech_pantheon': 'Открывает Алтарь',
  'tech_classical_era': 'Открывает +2 уровня юнитов, Гражданство',
  'tech_artisanship': 'Открывает Кузницу, Мастерскую лучника, Металл Т1, Меч Т1, Эндерлук Т1',
  'tech_iron_working': 'Открывает Лук Т1, Арбалет Т1, Топор Т1, Щит Т1',
  'tech_armory': 'Открывает Казармы, Воина, Лучника, Гоплита',
  'tech_productivity': 'Открывает Шахту, Лесопилку',
  'tech_pottery': 'Открывает Зернохранилище, Коттедж',
  'tech_calendar': 'Открывает Библиотеку',
  'tech_state_workforce': 'Открывает Хутор',
  'tech_brewing': 'Открывает Алхимическую лавку',
  'tech_masonry': 'Открывает Стрелковую башню, стены, Дозорную башню, стены и Проект улучшения цивилизации',
  'tech_toolsmithing': 'Открывает Металлургию, Оружейную',
  'tech_the_wheel': 'Открывает Ветряную мельницу, Лесопилку, +20 роста на Культурную зону',
  'tech_animal_husbandry': 'Открывает Пастбище, Конюшню',
  'tech_code_of_laws': 'Открывает Деревню, +10% монет из квестов',
  'tech_construction_site': 'Открывает Карьер, уровень Землечерпалки',
  'tech_land_taxes': 'Открывает +10% дохода Коттеджа, уровень Коттеджа',
  'tech_trading': 'Открывает Торговый форпост, уровень Лесопилки',
  'tech_writing': 'Открывает уровень Банка, уровень Коттеджа',
  'tech_monarchy': 'Открывает Большую деревню, уровень Коттеджа',
  'tech_antiquity_era': 'Открывает Поселенца, +2 уровня юнитов, +1 активного Вождя, +1 слот исследования Чуда',
  'tech_steel_working': 'Открывает Лук Т2, Арбалет Т2, Топор Т2, Щит Т2',
  'tech_craftsmanship': 'Открывает Кожу Т2, Металл Т2, Меч Т2, Эндерлук Т2',
  'tech_castles': 'Открывает Стену, +10 HP к Контрольным точкам',
  'tech_military_tradition': 'Открывает Инженера, военные звания юнитов',
  'tech_deep_mining': 'Открывает уровень Карьера, уровень Шахты',
  'tech_commerce': 'Открывает уровень Пастбища, уровень Лесопилки',
  'tech_horseback_riding': 'Открывает уровень Пастбища, +20% дальности передвижения',
  'tech_minting': 'Открывает уровень Банка, +10% дохода Коттеджа',
  'tech_barter': 'Открывает уровень Банка, Рынок',
  'tech_early_empire': 'Открывает уровень Коттеджа, Склад',
  'tech_foundation': 'Улучшения тайлов начинаются на уровень выше, уровень Башни, уровень Ветряной мельницы',
  'tech_sifting': 'Открывает уровень Землечерпалки, уровень Металлургии',
  'tech_sailing': 'Открывает Верфь, Рыболовное судно',
  'tech_conservation': 'Открывает Мясную лавку',
  'tech_priesthood': 'Открывает Храм, уровень Алхимической лавки',
  'tech_guilds': 'Открывает уровень Банка, Гильдию авантюристов',
  'tech_logistic': 'Открывает уровень Храма',
  'tech_gunpowder': 'Открывает Пушечную башню, стены, уровень Лесопилки, +0.25 молота за равнину и пустыню',
  'tech_open_field_excavation': 'Открывает уровень Шахты, уровень Карьера, +15 Культуры на Культурную зону',
  'tech_aquaculture': 'Открывает уровень Алх. лавки, уровень Оружейной, уровень Ветряной мельницы, +0.25 роста за Саванну и Меса',
  'tech_baking': 'Открывает Пекарню, уровень Пастбища',
  'tech_printing_press': 'Открывает +10% скорости Культуры',
  'tech_scholarship': 'Открывает уровень Библиотеки, уровень Алхимической лавки',
  'tech_global_trade': 'Открывает +1 множитель одинаковых торговых товаров',
  'tech_feudalism': 'Открывает Город, уровень Коттеджа',
  'tech_medieval_era': 'Открывает +2 уровня юнитов, +1 активного Вождя, +1 слот Чуда, покупку Экономических ОП каждые 7 дней, смену правительства (Города-государства), скидку 15% на науку/монеты',
  'tech_carbide_working': 'Открывает Лук Т3, Арбалет Т3, Топор Т3, Щит Т3',
  'tech_chemical_bonding': 'Открывает Металл Т3, Кожу Т3, Меч Т3, Эндерлук Т3',
  'tech_philosophy': 'Открывает уровень Коттеджа, уровень Библиотеки',
  'tech_mining_guilds': 'Открывает уровень Шахты, уровень Металлургии, +10% дохода Банка',
  'tech_rationalism': 'Открывает Лабораторию, уровень Алхимической лавки',
  'tech_exploration': 'Открывает Маяк, Разведывательный корабль',
  'tech_ritual': 'Открывает уровень Храма, уровень Рынка',
  'tech_currency': 'Открывает уровень Банка, уровень Мясной лавки',
  'tech_construction': 'Открывает Большой город, уровень Рынка',
  'tech_siege_tactics': 'Открывает +1 урон по стенам, 25% стоимости разрушенного строения монетами, +0.35 науки за лесной блок',
  'tech_branch_mining': 'Открывает +15% бонус плавки, +0.5 молота за Тайгу и Тундру',
  'tech_turbines': 'Открывает уровень Ветряной мельницы, +0.25 науки за блок Океана',
  'tech_importation': 'Открывает +1 счастья за торговый товар',
  'tech_ideology': 'Открывает +0.25 науки за блок джунглей и грибов',
  'tech_compass': 'Открывает Стрелковый корабль, Пушечный корабль, уровень Оружейной',
  'tech_education': 'Открывает уровень Библиотеки, уровень Лаборатории',
  'tech_taxation': 'Открывает уровень Пастбища, уровень Рынка',
  'tech_urbanization': 'Открывает уровень Башни, уровень Коттеджа',
  'tech_advanced_masonry': 'Улучшения тайлов начинаются на уровень выше, уровень Мясной лавки',
  'tech_fortification': 'Открывает Артиллерийскую башню, уровень Шахты, уровень Оружейной',
  'tech_machinery': 'Открывает уровень Коттеджа, уровень Мясной лавки, +25% скорости Пекарен и Землечерпалок',
  'tech_mercantile': 'Открывает Таверну, +10% торгового дохода',
  'tech_inquisition': 'Открывает уровень Храма, +0.005 счастья за блок пляжа и болота',
  'tech_energy_study': 'Открывает Башню Сияния, уровень Лаборатории',
  'tech_gears': 'Открывает уровень Пекарни, +15% бонус плавки',
  'tech_banking': 'Открывает уровень Банка, +15% монет из квестов',
  'tech_nationalism': 'Открывает Мегаполис, уровень Металлургии',
  'tech_sanitization': 'Открывает Больницу, уровень Пекарни, +1 рост за блок Реки',
  'tech_renaissance_era': 'Открывает +1 активного Вождя, +2 уровня юнитов, +1 слот Чуда',
  'tech_composite': 'Металл Т4, Кожа Т4, Меч Т4, Эндерлук Т4',
  'tech_titanium_working': 'Открывает Лук Т4, Арбалет Т4, Топор Т4, Щит Т4',
  'tech_communication': 'Открывает +400 базовой Культуры, -75% таймера анархии в Городах',
  'tech_advanced_efficiency': 'Открывает уровень Библиотеки, +1 XP строениям за каждый часовой тик',
  'tech_engineering': 'Открывает уровень Башни, +10% HP строений',
  'tech_replaceable_parts': 'Открывает уровень Мясной лавки, +20 молотов и +10 науки на Культурную зону',
  'tech_tourism': 'Открывает уровень Рынка, +20% дальности на Конюшнях/Верфях',
  'tech_civil_service': 'Открывает уровень Землечерпалки, уровень Ветряной мельницы',
  'tech_trade_networks': 'Открывает +1 множитель одинаковых торговых товаров',
  'tech_economics': 'Открывает уровень Банка',
  'tech_agency': 'Открывает уровень Лаборатории, уровень Алхимической лавки',
  'tech_politics': 'Открывает Большой мегаполис, уровень Башни',
  'tech_core_mining': 'Открывает уровень Карьера, уровень Землечерпалки, уровень Шахты, уровень Металлургии',
  'tech_radio': 'Открывает +20% опыта юнитов, -10% стоимости Продвижений юнитов (Молот и Рост)',
  'tech_globalization': 'Открывает уровень Храма, +1 Культурную зону всем городам Цивилизации и ещё +1 при наличии улучшения Метрополис',
  'tech_industrialization': 'Открывает уровень Оружейной, +4 слота улучшений тайлов в каждом городе',
  'tech_world_trade': 'Открывает уровень Банка, уровни Метрополиса и Столицы',
  'tech_cultural_heritage': 'Открывает уровень Храма, +5% скорости Культуры за торговый товар',
  'tech_experimentation': 'Открывает Тайную башню, уровень Лаборатории',
  'tech_stock_market': 'Открывает уровень Банка',
  'tech_capitalism': 'Открывает +1 множитель одинаковых торговых товаров',
  'tech_hydroponics': 'Открывает уровень Пастбища, уровень Пекарни, Пастбищу требуется 750 роста вместо 1000 за бонусное яйцо',
  'tech_industrial_era': 'Открывает +1 уровень юнитов, +1 слот Чуда',
  'tech_abyssal_composites': 'Металл Т5, Кожа Т5, Меч Т5, Эндерлук Т5',
  'tech_abyssal_working': 'Открывает Лук Т5, Арбалет Т5, Топор Т5, Щит Т5',
  'tech_council_of_eight': 'Открывает Совет Восьми',
  'tech_robotics': '3 ОП за первого юнита 10 уровня; 1 ОП в неделю за каждый уникальный тип военного юнита 10 уровня',
  'tech_enlightenment': '3 ОП при завершении; 1 ОП в неделю',
  'tech_great_pyramid': 'Открывает Великую пирамиду',
  'tech_great_lighthouse': 'Открывает Александрийский маяк',
  'tech_hanging_gardens': 'Открывает Висячие сады',
  'tech_colossus': 'Открывает Колосс',
  'tech_grand_ship_ingermanland': 'Открывает Флагман Ингерманланд',
  'tech_taj_mahal': 'Открывает Тадж-Махал',
  'tech_temple_of_artemis': 'Открывает Храм Артемиды',
  'tech_statue_of_liberty': 'Открывает Статую Свободы',
  'tech_notre_dame': 'Открывает Нотр-Дам',
  'tech_colosseum': 'Открывает Колизей',
  'tech_global_stock_exchange': 'Открывает Глобальную биржу',
  'tech_oxford_university': 'Открывает Оксфордский университет',
  'tech_himeji': 'Открывает Замок Химэдзи',
  'tech_kremlin': 'Открывает Кремль',
  'tech_huey_teocalli': 'Открывает Уэй Теокалли',
  'tech_porcelain_tower': 'Открывает Фарфоровую башню',
  'tech_angkor_wat': 'Открывает Ангкор-Ват',
  'tech_great_library': 'Открывает Александрийскую библиотеку',
  'tech_chichen_itza': 'Открывает Чичен-Ицу',
  'tech_big_ben': 'Открывает Биг-Бен',
  'tech_globe_theatre': 'Открывает Глобус (Театр)',
  'tech_oracle': 'Открывает Оракул',
  'tech_brandenburg_gate': 'Открывает Бранденбургские ворота',
};

// ── Layout ─────────────────────────────────────
const LAYOUT = [
  ['tech_ancient_era'],
  ['tech_belief'],
  ['tech_mining', 'tech_agriculture', 'tech_laws', 'tech_pantheon'],
  ['tech_classical_era'],
  ['tech_artisanship', 'tech_iron_working', 'tech_armory', 'tech_productivity', 'tech_pottery', 'tech_calendar', 'tech_state_workforce', 'tech_brewing'],
  ['tech_masonry', 'tech_toolsmithing', 'tech_the_wheel', 'tech_animal_husbandry', 'tech_code_of_laws'],
  ['tech_construction_site', 'tech_land_taxes', 'tech_trading', 'tech_writing', 'tech_monarchy'],
  ['tech_antiquity_era'],
  ['tech_steel_working', 'tech_craftsmanship', 'tech_castles', 'tech_military_tradition', 'tech_deep_mining', 'tech_commerce', 'tech_horseback_riding', 'tech_minting', 'tech_barter', 'tech_early_empire'],
  ['tech_foundation', 'tech_sifting', 'tech_sailing', 'tech_conservation', 'tech_priesthood', 'tech_guilds'],
  ['tech_logistic', 'tech_gunpowder', 'tech_open_field_excavation', 'tech_aquaculture', 'tech_baking', 'tech_printing_press', 'tech_scholarship', 'tech_global_trade', 'tech_feudalism'],
  ['tech_medieval_era'],
  ['tech_carbide_working', 'tech_chemical_bonding', 'tech_philosophy', 'tech_mining_guilds', 'tech_rationalism', 'tech_exploration', 'tech_ritual', 'tech_currency', 'tech_construction'],
  ['tech_siege_tactics', 'tech_branch_mining', 'tech_turbines', 'tech_importation', 'tech_ideology', 'tech_compass', 'tech_education', 'tech_taxation', 'tech_urbanization', 'tech_advanced_masonry'],
  ['tech_fortification', 'tech_machinery', 'tech_mercantile', 'tech_inquisition', 'tech_energy_study', 'tech_gears', 'tech_banking', 'tech_nationalism', 'tech_sanitization'],
  ['tech_renaissance_era'],
  ['tech_composite', 'tech_titanium_working', 'tech_communication', 'tech_advanced_efficiency', 'tech_engineering', 'tech_replaceable_parts', 'tech_tourism', 'tech_civil_service', 'tech_trade_networks', 'tech_economics', 'tech_agency', 'tech_politics', 'tech_core_mining'],
  ['tech_radio', 'tech_globalization', 'tech_industrialization', 'tech_world_trade', 'tech_cultural_heritage', 'tech_experimentation', 'tech_stock_market', 'tech_capitalism', 'tech_hydroponics'],
  ['tech_industrial_era'],
  ['tech_abyssal_composites', 'tech_abyssal_working', 'tech_council_of_eight'],
  ['tech_robotics', 'tech_enlightenment'],
];

const NW = 148, NH = 96, CG = 44, RG = 20;
const WCOLS = 3;
